### ISSUE TITLE
Compiling the book

### ISSUE THREAD

**Issue by acortell3** [acortell3/archaeoriddle#28]
Probably it's just me, but I'm struggling with this

bookdown::render_book(".",output_dir="/var/www/html/archaeoriddle/")

and if I am, there'll be more people once it is open, I'd believe?

**Comment by simoncarrignon** [comment]
@acortell3 I think we are good with that no? or do we _really_  want someone to tyr with windows :'D

**Comment by acortell3** [comment]
Yeah, we should be good. Screw windows! :-D Closing this
