### ISSUE TITLE
Order chapters

### ISSUE THREAD

**Issue by acortell3** [acortell3/archaeoriddle#34]
I think we should change the order of the chapters. That order is there just because we code it like that, but I don't think it makes a lot of sense to start with the generation and loss of the record before explaining the full model.
I'll write a blurb in the preface explaining this and other things we've been discussing, but still, what do you think? I'd do 01_Generate_environment / 02_Spatial_growth / 03_Record_formation / 04_Record_loss / 05_Selected_simulation / 06_generating_arch_record
What do you think?

**Comment by acortell3** [comment]
I included a little blurb for the intro and changed the order of the chapters. Check it out to see what you think!

**Comment by simoncarrignon** [comment]
looks good with me! can close if you want
