### ISSUE TITLE
Probs

### ISSUE THREAD

**Issue by acortell3** [acortell3/archaeoriddle#6]
These values need more research. In any case, probably it would be better to set them as a probability. Maybe as a gamma centred in those values?

https://github.com/acortell3/collaborabm/blob/b26b6614ec1d24eb903196f05a9fc20e6f7f54d2/doc/bookdown/01_Record_formation.Rmd#L360-L373

**Comment by simoncarrignon** [comment]
has it been solve @acortell3 ?

**Comment by acortell3** [comment]
Yeah, this was with the creation of model actually. We can't do anything now because we can't change the model, so closing this issue
